name: talentscan_ai
description: AI-Powered Sports Talent Assessment Platform

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.0
  video_player: ^2.6.0
  lottie: ^2.3.0
  animated_text_kit: ^4.2.2
  fl_chart: ^0.68.0  
  shimmer: ^3.0.0
  google_fonts: ^4.0.0
  shared_preferences: ^2.1.0
  image_picker: ^0.8.7
  percent_indicator: ^4.2.1
  confetti: ^0.7.0
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
